version: '3.8'

services:
  secure-proxy:
    build: .
    ports:
      - "443:3000"
    environment:
      - PORT=3000
      - XAPI_KEY=${XAPI_KEY}
      - XAPI_SECRET=${XAPI_SECRET}
      - XAPI_ENDPOINT=${XAPI_ENDPOINT}
      - CORS_ORIGIN=${CORS_ORIGIN}
      - SSL_KEY_PATH=${SSL_KEY_PATH}
      - SSL_CERT_PATH=${SSL_CERT_PATH}
    volumes:
      - ./certs:/usr/src/app/certs
    restart: unless-stopped